#!/sbin/busybox sh

# $1 - "core_mask"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	core_mask=$2;

	case "${core_mask}" in
		1)
			# All cores goes off
			echo 255 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		2)
			# b2l2
			echo 200 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		3)
			# b4
			echo 240 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		4)
			# b2
			echo 250 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		5)
			# l4
			echo 14 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		6)
			# l4b2
			echo 8 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		7)
			# l3b3
			echo 45 > /cputemp/core_control_mask;
			echo 80 > /cputemp/core_limit_temp_degC;
			sleep 1;
			echo $core_limit_temp_degC > /cputemp/core_limit_temp_degC;

			$BB sh /res/uci.sh cpu_b_max_freq &cpu_b_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_b_min_freq &cpu_b_min_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_max_freq &cpu_l_max_freq > /dev/null;
			$BB sh /res/uci.sh cpu_l_min_freq &cpu_l_min_freq > /dev/null;

			$BB sh /res/uci.sh core_ctrl_b_max &core_ctrl_b_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_b_min &core_ctrl_b_min > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_max &core_ctrl_l_max > /dev/null;
			$BB sh /res/uci.sh core_ctrl_l_min &core_ctrl_l_min > /dev/null;
		;;
		*)
			core_mask=1;
		;;
	esac;
fi;

echo ${core_mask};
