#!/sbin/busybox sh

# $1 - "vtg_level"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	vtg_level=$2;

	vib_level=$(lua -e "print (math.floor((vtg_level * 34.8) + 116))");
#	vib_level=$(lua -e "print (math.floor((vtg_level - 116) / 34.8))");
	echo "$vib_level" > /sys/class/timed_output/vibrator/vtg_level;
fi;

echo ${vtg_level};
