#!/sbin/busybox sh

(
BB=/gabriel/busybox

	$BB mount -o remount,rw /system;

if [ "$(cat /system/usr/keylayout/Generic.kl | grep "key 139   MENU" | wc -l)" -gt 0 ]; then
  $BB cp /system/usr/keylayout/Generic.kl /system/usr/keylayout/Generic.kl.bak;
  sed -i 's/key 139   MENU/key 139   APP_SWITCH/g' /system/usr/keylayout/Generic.kl;
  sed -i 's/key 580   APP_SWITCH/key 580   MENU/g' /system/usr/keylayout/Generic.kl;
  echo "key layout has been patched";
else
  echo "no need to patch key layout";
fi;

	$BB mount -o remount,ro /system;
)&
