#!/sbin/busybox sh

# $1 - "core_ctrl_b_min"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_b_min=$2;

	case "${core_ctrl_b_min}" in
		0)
			BMAXCPUS="$(cat /sys/devices/system/cpu/cpu0/core_ctl/max_cpus)";
			echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
			echo $BMAXCPUS > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;

			echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
			$BB sync
		;;
		1)
			BMAXCPUS="$(cat /sys/devices/system/cpu/cpu0/core_ctl/max_cpus)";
			echo 1 > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
			echo $BMAXCPUS > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;

			echo 1 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
			$BB sync
		;;
		2)
			BMAXCPUS="$(cat /sys/devices/system/cpu/cpu0/core_ctl/max_cpus)";
			echo 2 > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
			echo $BMAXCPUS > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;

			echo 2 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
			$BB sync
		;;
		3)
			BMAXCPUS="$(cat /sys/devices/system/cpu/cpu0/core_ctl/max_cpus)";
			echo 3 > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
			echo $BMAXCPUS > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;

			echo 3 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
			$BB sync
		;;
		4)
			BMAXCPUS="$(cat /sys/devices/system/cpu/cpu0/core_ctl/max_cpus)";
			echo 4 > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;
			echo $BMAXCPUS > /sys/devices/system/cpu/cpu0/core_ctl/max_cpus;

			echo 4 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus;
			$BB sync
		;;
		*)
			core_ctrl_b_min=2;
		;;
	esac;
fi;

echo ${core_ctrl_b_min};
