#!/sbin/busybox sh

# $1 - "core_ctrl_b_min"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_b_min=$2;

	case "${core_ctrl_b_min}" in
		0)
			echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
			$BB sync
		;;
		1)
			echo 1 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
			$BB sync
		;;
		2)
			echo 2 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
			$BB sync
		;;
		3)
			echo 3 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
			$BB sync
		;;
		4)
			echo 4 > /sys/devices/system/cpu/cpu0/core_ctl/min_cpus
			$BB sync
		;;
		*)
			core_ctrl_b_min=2;
		;;
	esac;
fi;

echo ${core_ctrl_b_min};
