#!/sbin/busybox sh

# $1 - "core_ctrl_b_preference"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_b_preference=$2;

	case "${core_ctrl_b_preference}" in
		yes)
			echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/not_preferred;
			$BB sync
		;;
		no)
			echo 1 > /sys/devices/system/cpu/cpu0/core_ctl/not_preferred;
			$BB sync
		;;
		*)
			core_ctrl_b_preference=yes;
		;;
	esac;
fi;

echo ${core_ctrl_b_preference};
