#!/sbin/busybox sh

# $1 - "core_ctrl_l_min"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_l_min=$2;

	case "${core_ctrl_l_min}" in
		0)
			LMAXCPUS="$(cat /sys/devices/system/cpu/cpu4/core_ctl/max_cpus)";
			echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
			echo $LMAXCPUS > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;

			echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			$BB sync
		;;
		1)
			LMAXCPUS="$(cat /sys/devices/system/cpu/cpu4/core_ctl/max_cpus)";
			echo 1 > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
			echo $LMAXCPUS > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;

			echo 1 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			$BB sync
		;;
		2)
			LMAXCPUS="$(cat /sys/devices/system/cpu/cpu4/core_ctl/max_cpus)";
			echo 2 > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
			echo $LMAXCPUS > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;

			echo 2 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			$BB sync
		;;
		3)
			LMAXCPUS="$(cat /sys/devices/system/cpu/cpu4/core_ctl/max_cpus)";
			echo 3 > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
			echo $LMAXCPUS > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;

			echo 3 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			$BB sync
		;;
		4)
			LMAXCPUS="$(cat /sys/devices/system/cpu/cpu4/core_ctl/max_cpus)";
			echo 4 > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;
			echo $LMAXCPUS > /sys/devices/system/cpu/cpu4/core_ctl/max_cpus;

			echo 4 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			$BB sync
		;;
		*)
			core_ctrl_l_min=4;
		;;
	esac;
fi;

echo ${core_ctrl_l_min};
