#!/sbin/busybox sh

# $1 - "core_ctrl_l_up_thres"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_l_up_thres=$2;

	echo $core_ctrl_l_up_thres > /sys/devices/system/cpu/cpu4/core_ctl/busy_up_thres;
	$BB sync

fi;

echo ${core_ctrl_l_up_thres};
