#!/sbin/busybox sh

# $1 - "core_ctrl_b_task_thres"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_b_task_thres=$2;

	echo $core_ctrl_b_task_thres > /sys/devices/system/cpu/cpu0/core_ctl/task_thres;
	$BB sync

fi;

echo ${core_ctrl_b_task_thres};
