#!/sbin/busybox sh

# $1 - "core_ctrl_l_off_delay"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	core_ctrl_l_off_delay=$2;

	echo $core_ctrl_l_off_delay > /sys/devices/system/cpu/cpu4/core_ctl/offline_delay_ms;
	$BB sync

fi;

echo ${core_ctrl_l_off_delay};
