#!/sbin/busybox sh

# $1 - "cpu_b_max_freq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "$cortexbrain_cpu" == "on" ]; then
	if [ "a$2" != "a" ]; then
		cpu_b_max_freq=$2;

		for i in cpu0 cpu1 cpu2 cpu3; do
			echo $cpu_b_max_freq > /sys/devices/system/cpu/$i/cpufreq/scaling_max_freq
		done;

		echo "0:$cpu_b_max_freq 1:$cpu_b_max_freq 2:$cpu_b_max_freq 3:$cpu_b_max_freq" > /sys/module/msm_performance/parameters/cpu_max_freq

	fi;
fi;

echo ${cpu_b_max_freq};
