#!/sbin/busybox sh

# $1 - "cpu_b_interactive_profile_boost"
# $2 - value=
# Created By Dorimanx

BB=/gabriel/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_b_interactive_profile_boost=$2;

	case "${cpu_b_interactive_profile_boost}" in
		enable)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					echo 1 > /$CPUB/$GOV/boost
					break
				fi;
			done;

			$BB sync
		;;
		disable)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					echo 0 > /$CPUB/$GOV/boost
					break
				fi;
			done;

			$BB sync
		;;
		*)
			cpu_b_interactive_profile_boost=disable;
		;;
	esac;
fi;

echo ${cpu_b_interactive_profile_boost};
