#!/sbin/busybox sh

# $1 - "cpu_l_interactive_profile"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_l_interactive_profile=$2;

	case "${cpu_l_interactive_profile}" in
		off)
			$BB sleep 0.5s
			$BB sync
		;;
		balance)
			TARGET4="1 768000:35 902400:50 998400:80 1094400:100"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 0 > /$CPUL/$GOV/use_sched_load
					echo 0 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 0 > /$CPUL/$GOV/above_hispeed_delay
					echo 300 > /$CPUL/$GOV/go_hispeed_load
					echo 1094400 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 40000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 0 > /$CPUL/$GOV/min_sample_time
					echo 1 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo -1 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 80000 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		xanax_battery_extreme)
			TARGET4="71 768000:70 902400:77 998400:87 1094400:99"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 0 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 10000 > /$CPUL/$GOV/above_hispeed_delay
					echo 155 > /$CPUL/$GOV/go_hispeed_load
					echo 768000 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 86666 > /$CPUL/$GOV/timer_rate
					echo 86666 > /$CPUL/$GOV/sleep_timer_rate
					echo 23000 > /$CPUL/$GOV/min_sample_time
					echo 0 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo 145000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 1 > /$CPUL/$GOV/boost
					echo 0 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		nlb_performance)
			TARGET4="1 768000:40 902400:65 998400:75 1094400:95"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 0 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 0 > /$CPUL/$GOV/above_hispeed_delay
					echo 300 > /$CPUL/$GOV/go_hispeed_load
					echo 998400 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 20000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 0 > /$CPUL/$GOV/min_sample_time
					echo 1 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo -1 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 1 > /$CPUL/$GOV/boost
					echo 0 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		bef_gaming)
			TARGET4="50 902400:69"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 1 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 0 > /$CPUL/$GOV/above_hispeed_delay
					echo 75 > /$CPUL/$GOV/go_hispeed_load
					echo 998400 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 20000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 40000 > /$CPUL/$GOV/min_sample_time
					echo 1 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 79000 > /$CPUL/$GOV/max_freq_hysteresis
					echo 80000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 0 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		gabriel)
			TARGET4="80"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 1 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 10000 > /$CPUL/$GOV/above_hispeed_delay
					echo 80 > /$CPUL/$GOV/go_hispeed_load
					echo 998400 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 20000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 80000 > /$CPUL/$GOV/min_sample_time
					echo 1 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 99000 > /$CPUL/$GOV/max_freq_hysteresis
					echo 80000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 0 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		glassfish)
			TARGET4="80 768000:70 902400:99"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 0 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 0 > /$CPUL/$GOV/above_hispeed_delay
					echo 91 > /$CPUL/$GOV/go_hispeed_load
					echo 902400 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 60000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 0 > /$CPUL/$GOV/min_sample_time
					echo 1 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo 480000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 0 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		miui)
			TARGET4="1 768000:90"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 1 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 39000 > /$CPUL/$GOV/above_hispeed_delay
					echo 90 > /$CPUL/$GOV/go_hispeed_load
					echo 768000 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 20000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 40000 > /$CPUL/$GOV/min_sample_time
					echo 0 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo 80000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 80000 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		pixel)
			TARGET4="90"

			for i in 4 5 6 7; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
			    if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUL/scaling_governor);
					chmod 644 /$CPUL/$GOV/*
					echo 1 > /$CPUL/$GOV/use_sched_load
					echo 1 > /$CPUL/$GOV/use_migration_notif
					echo 0 > /$CPUL/$GOV/enable_prediction
					echo 20000 > /$CPUL/$GOV/above_hispeed_delay
					echo 99 > /$CPUL/$GOV/go_hispeed_load
					echo 1209600 > /$CPUL/$GOV/hispeed_freq
					echo "$TARGET4" > /$CPUL/$GOV/target_loads
					echo 20000 > /$CPUL/$GOV/timer_rate
					echo 40000 > /$CPUL/$GOV/sleep_timer_rate
					echo 80000 > /$CPUL/$GOV/min_sample_time
					echo 0 > /$CPUL/$GOV/ignore_hispeed_on_notif
					echo 0 > /$CPUL/$GOV/max_freq_hysteresis
					echo 80000 > /$CPUL/$GOV/timer_slack
					echo 0 > /$CPUL/$GOV/io_is_busy
					echo 0 > /$CPUL/$GOV/boost
					echo 80000 > /$CPUL/$GOV/boostpulse_duration
					echo 0 > /$CPUL/$GOV/fast_ramp_down
					break
				fi;
			done;

			$BB sync
		;;
		*)
			cpu_l_interactive_profile=off;
		;;
	esac;
fi;

echo ${cpu_l_interactive_profile};
