#!/sbin/busybox sh

# $1 - "cpu_b_interactive_profile_hisp_freq"
# $2 - value=
# Created By Dorimanx

BB=/gabriel/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_b_interactive_profile_hisp_freq=$2;

	for i in 0 1 2 3; do
		CPUB=sys/devices/system/cpu/cpu$i/cpufreq
		if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
			GOV=$(cat /$CPUB/scaling_governor);
			echo $cpu_b_interactive_profile_hisp_freq > /$CPUB/$GOV/hispeed_freq
			break
		fi;
	done;
fi;

echo ${cpu_b_interactive_profile_hisp_freq};
