#!/sbin/busybox sh

# $1 - "cpu_l_interactive_profile_hisp_freq"
# $2 - value=
# Created By Dorimanx

BB=/gabriel/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_l_interactive_profile_hisp_freq=$2;

	for i in 4 5 6 7; do
		CPUL=sys/devices/system/cpu/cpu$i/cpufreq
		if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
			GOV=$(cat /$CPUL/scaling_governor);
			echo $cpu_l_interactive_profile_hisp_freq > /$CPUL/$GOV/hispeed_freq
			break
		fi;
	done;
fi;

echo ${cpu_l_interactive_profile_hisp_freq};
