#!/sbin/busybox sh

# $1 - "cpu_b_gov_profile"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	cpu_b_gov_profile=$2;

	case "${cpu_b_gov_profile}" in
		off)
			$BB sleep 0.5s
			$BB sync
		;;
		relaxed_default)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 12 > /$CPUB/$GOV/boost_ceiling
					echo 8 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 35 > /$CPUB/$GOV/down_threshold
					echo 45 > /$CPUB/$GOV/down_threshold_suspended
					echo 5 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 85 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		chill_default)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 8 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 35 > /$CPUB/$GOV/down_threshold
					echo 45 > /$CPUB/$GOV/down_threshold_suspended
					echo 5 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 85 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		relaxed_balance)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 10 > /$CPUB/$GOV/boost_ceiling
					echo 5 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 60 > /$CPUB/$GOV/down_threshold
					echo 85 > /$CPUB/$GOV/down_threshold_suspended
					echo 6 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 70 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		chill_balance)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 10 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 75 > /$CPUB/$GOV/down_threshold
					echo 99 > /$CPUB/$GOV/down_threshold_suspended
					echo 4 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 90 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		relaxed_battery)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 12 > /$CPUB/$GOV/boost_ceiling
					echo 6 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 70 > /$CPUB/$GOV/down_threshold
					echo 85 > /$CPUB/$GOV/down_threshold_suspended
					echo 6 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 75 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		chill_battery)
			for i in 0 1 2 3; do
				CPUB=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV=$(cat /$CPUB/scaling_governor);
					chmod 644 /$CPUB/$GOV/*
					echo 12 > /$CPUB/$GOV/boost_count
					echo 1 > /$CPUB/$GOV/boost_enabled
					echo 75 > /$CPUB/$GOV/down_threshold
					echo 99 > /$CPUB/$GOV/down_threshold_suspended
					echo 4 > /$CPUB/$GOV/freq_step
					echo 0 > /$CPUB/$GOV/ignore_nice_load
					echo 90 > /$CPUB/$GOV/up_threshold
					break
				fi;
			done;

			$BB sync
		;;
		*)
			cpu_b_gov_profile=off;
		;;
	esac;
fi;

echo ${cpu_b_gov_profile};
