#!/sbin/busybox sh

# $1 - "default_cpu_l_gov"
# $2 - value=
# Created By Dorimanx

BB=/gabriel/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	default_cpu_l_gov=$2;

if [ -d /sys/devices/system/cpu/cpufreq/policy4 ];then

	CPUL=sys/devices/system/cpu/cpufreq/policy4
	if [ "$(cat /sys/devices/system/cpu/cpu4/core_ctl/min_cpus)" == "0" ];then
		echo 1 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
		LMINCPUS=0;
	fi;

	chmod 644 /$CPUL/scaling_governor
	echo "$default_cpu_l_gov" > /$CPUL/scaling_governor;
	CPUGOV4="$(cat /$CPUL/scaling_governor)";
	chmod 444 /$CPUL/scaling_governor
	if [ "LMINCPUS" -eq "0" ];then
		echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
	fi;

else

	for i in 4 5 6 7; do
		CPUL=sys/devices/system/cpu/cpu$i/cpufreq
		if [ "$(cat /sys/devices/system/cpu/cpu4/core_ctl/min_cpus)" == "0" ];then
			echo 1 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			LMINCPUS=0;
		fi;

		if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
			chmod 644 /$CPUL/scaling_governor
			echo "$default_cpu_l_gov" > /$CPUL/scaling_governor;
			CPUGOV4="$(cat /$CPUL/scaling_governor)";
			chmod 444 /$CPUL/scaling_governor
			if [ "LMINCPUS" -eq "0" ];then
				echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
			fi;
			break
		fi;
	done;

fi;

	if [ "$CPUGOV4" = "interactive" ] ||
		[ "$CPUGOV4" = "gabriel" ] ||
		[ "$CPUGOV4" = "gabrielplus" ] ||
		[ "$CPUGOV4" = "impulse" ] ||
		[ "$CPUGOV4" = "cultivation" ]; then
		$BB sh /res/uci.sh cpu_l_interactive_profile $cpu_l_interactive_profile > /dev/null;
		$BB sh /res/uci.sh cpu_l_interactive_profile_boost $cpu_l_interactive_profile_boost > /dev/null;
		$BB sh /res/uci.sh cpu_l_interactive_profile_hisp_freq $cpu_l_interactive_profile_hisp_freq > /dev/null;
		if [ "$CPUGOV4" = "gabriel" ] ||
		   [ "$CPUGOV4" = "gabrielplus" ]; then
			$BB sh /res/uci.sh idle_threshold_gabriel_l $idle_threshold_gabriel_l > /dev/null;
			$BB sh /res/uci.sh sample_rate_gabriel_l $sample_rate_gabriel_l > /dev/null;
			$BB sh /res/uci.sh max_l_l_gabriel_l $max_l_l_gabriel_l > /dev/null;
			$BB sh /res/uci.sh samp_d_f_gabriel_l $samp_d_f_gabriel_l > /dev/null;
			$BB sh /res/uci.sh two_phase_freq_gabriel_l $two_phase_freq_gabriel_l > /dev/null;
			$BB sh /res/uci.sh freq_calc_t_gabriel_l $freq_calc_t_gabriel_l > /dev/null;
		fi;
	elif [ "$CPUGOV4" = "chill" ] ||
		[ "$CPUGOV4" = "relaxed" ]; then
		$BB sh /res/uci.sh cpu_l_gov_profile $cpu_l_gov_profile > /dev/null;
	fi;

	if [ -e /res/uci_boot.sh ]; then
		$BB sh /res/uci_boot.sh power_mode $power_mode > /dev/null;
	else
		$BB sh /res/uci.sh power_mode $power_mode > /dev/null;
	fi;
fi;

echo ${default_cpu_l_gov};
