#!/sbin/busybox sh

# $1 - "default_cpu_l_gov"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	default_cpu_l_gov=$2;

for i in 4 5 6 7; do
	CPUL=sys/devices/system/cpu/cpu$i/cpufreq
	if [ "$(cat /sys/devices/system/cpu/cpu4/core_ctl/min_cpus)" == "0" ];then
		echo 1 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
		LMINCPUS=0;
	fi;

	if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
		chmod 644 /$CPUL/scaling_governor
		echo "$default_cpu_l_gov" > /$CPUL/scaling_governor;
		chmod 444 /$CPUL/scaling_governor
		if [ "LMINCPUS" -eq "0" ];then
			echo 0 > /sys/devices/system/cpu/cpu4/core_ctl/min_cpus;
		fi;
        break
    fi;
done;

	if [ -e /res/uci_boot.sh ]; then
		/res/uci_boot.sh power_mode $power_mode > /dev/null;
	else
		/res/uci.sh power_mode $power_mode > /dev/null;
	fi;
fi;

echo ${default_cpu_l_gov};
