#!/sbin/busybox sh

# $1 - "input_boost_freq_lc"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	input_boost_freq_lc=$2;

	for i in 4 5 6 7; do
		echo $i:$input_boost_freq_lc > /sys/module/cpu_boost/parameters/input_boost_freq;
	done;
fi;

echo ${input_boost_freq_lc};
