#!/sbin/busybox sh

# $1 - "oom_config_screen_on"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo $oom_config_screen_on;
else
	oom_config_screen_on=$2;
	echo "$oom_config_screen_on";
fi;

stweak_pid="$(pgrep -f stweak)";
echo "-1000" > /proc/$stweak_pid/oom_score_adj;

PROFILE=`cat /data/.gabriel/.active.profile`;

case "${oom_config_screen_on}" in
	verylight)
		echo "18432,23040,24576,28672,31744,34816" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "48" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	light)
		echo "18432,23040,27648,32356,46080,51200" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "32" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	medium)
		echo "18432,23040,27648,32356,49152,61440" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "32" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	stock)
		echo "12288,15360,18432,21504,24576,30720" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "32" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	miui)
		echo "18432,23040,27648,32256,55296,80640" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "32" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	aggressive)
		echo "18432,23040,27648,34816,51200,65536" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "16" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	exterminate)
		echo "18432,23040,27648,53760,58880,65536" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "16" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	gabriel)
		echo "18432,23040,27648,51256,89600,115200" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "32" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	gabriel_ext)
		echo "18432,23040,27648,51256,150296,200640" > /sys/module/lowmemorykiller/parameters/minfree;
		echo "16" > /sys/module/lowmemorykiller/parameters/cost;
	;;
	*)
		oom_config_screen_on=stock;
	;;
esac;
