#!/sbin/busybox sh

# $1 - "power_mode"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	power_mode=$2;

	GOV0_NAME=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);

	case "${power_mode}" in
		1)
			for i in 0 1 2 3; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV0_NAME=$(cat /$CPUL/scaling_governor);
					echo "10000" > /$CPUL/$GOV0_NAME/sampling_rate;
					echo "10000" > /$CPUL/$GOV0_NAME/timer_rate;
					echo "10000" > /$CPUL/$GOV0_NAME/min_sample_time;
			        break
			    fi;
			done;

			for i in 0 1 2 3; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV0_NAME=$(cat /$CPUL/scaling_governor);
					echo "10000" > /$CPUL/$GOV0_NAME/sampling_rate;
					echo "10000" > /$CPUL/$GOV0_NAME/timer_rate;
					echo "10000" > /$CPUL/$GOV0_NAME/min_sample_time;
			        break
			    fi;
			done;
		;;
		0)
			for i in 0 1 2 3; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV0_NAME=$(cat /$CPUL/scaling_governor);
					echo "$sample_rate_c1" > /$CPUL/$GOV0_NAME/sampling_rate;
					echo "$sample_rate_c1" > /$CPUL/$GOV0_NAME/timer_rate;
					echo "$sample_rate_c1" > /$CPUL/$GOV0_NAME/min_sample_time;
			        break
			    fi;
			done;

			for i in 0 1 2 3; do
				CPUL=sys/devices/system/cpu/cpu$i/cpufreq
				if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
					GOV0_NAME=$(cat /$CPUL/scaling_governor);
					echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/sampling_rate;
					echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/timer_rate;
					echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/min_sample_time;
			        break
			    fi;
			done;
		;;
		*)
			power_mode=0;
		;;
	esac;
fi;

echo ${power_mode};
