#!/sbin/busybox sh

# Recent Key Fix
# $1 - "recent_key_fix"
# $2 - value=

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	recent_key_fix=$2;

	case "${recent_key_fix}" in
		menu)
			if [ `cat /data/.gabriel/logs/recent_key_fix` -eq "1" ] || [ ! -e /data/.gabriel/logs/recent_key_fix ];then
				$BB mount -o remount,rw /system;
				sed -i 's/key 139   APP_SWITCH/key 139   MENU/g' /system/usr/keylayout/Generic.kl;
				sed -i 's/key 580   MENU/key 580   APP_SWITCH/g' /system/usr/keylayout/Generic.kl;
				$BB mount -o remount,ro /system;

				echo 0 > /data/.gabriel/logs/recent_key_fix;
			fi;
		;;
		app_switch)
			if [ `cat /data/.gabriel/logs/recent_key_fix` -eq "0" ] || [ ! -e /data/.gabriel/logs/recent_key_fix ];then
				$BB mount -o remount,rw /system;
				sed -i 's/key 139   MENU/key 139   APP_SWITCH/g' /system/usr/keylayout/Generic.kl;
				sed -i 's/key 580   APP_SWITCH/key 580   MENU/g' /system/usr/keylayout/Generic.kl;
				$BB mount -o remount,ro /system;

				echo 1 > /data/.gabriel/logs/recent_key_fix;
			fi;
		;;
		*)
			recent_key_fix=menu;
		;;
	esac;
fi;

echo ${recent_key_fix};
