#!/sbin/busybox sh

# $1 - "sample_rate_gabriel_b"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ] && [ "$power_mode" -eq "0" ]; then
	sample_rate_gabriel_b=$2;

	for i in 0 1 2 3; do
		CPUB=sys/devices/system/cpu/cpu$i/cpufreq
		if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
			GOV0_NAME=$(cat /$CPUB/scaling_governor);
			echo "$sample_rate_gabriel_b" > /$CPUB/$GOV0_NAME/timer_rate_idle;
	        break
	    fi;
	done;

fi;

echo ${sample_rate_gabriel_b};
