#!/sbin/busybox sh

# $1 - "sample_rate_c2"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ] && [ "$power_mode" -eq "0" ]; then
	sample_rate_c2=$2;

	for i in 4 5 6 7; do
		CPUL=sys/devices/system/cpu/cpu$i/cpufreq
		if [ "$(cat /sys/devices/system/cpu/cpu$i/online)" == "1" ];then
			GOV0_NAME=$(cat /$CPUL/scaling_governor);
			echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/sampling_rate;
			echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/timer_rate;
			echo "$sample_rate_c2" > /$CPUL/$GOV0_NAME/min_sample_time;
	        break
	    fi;
	done;

fi;

echo ${sample_rate_c2};
