#!/sbin/busybox sh

# $1 - "usb_adb"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	usb_adb=$2;

	case "${usb_adb}" in
		rom)
			$BB sync;
		;;
		none)
			settings put global adb_enabled 0
			$BB sync;
		;;
		adb)
			settings put global adb_enabled 1
			$BB sync;
		;;
		*)
			usb_adb=rom;
		;;
	esac;
fi;

echo ${usb_adb};
